/// <mls fileReference="_102033_/l2/shared/layout/aura-header-base.ts" enhancement="_blank" />

// Base of EVERY client header: the master's own (`collab-aura-header`) and the per-project ones
// generated by agentGenerateHeader. It owns the invariants the shell depends on, which used to live
// as comments and convention inside a single header file:
//
//   * light DOM (`createRenderRoot`) — the shell styles region descendants and the DS tokens are on :root;
//   * the `<header>` band filling `--aura-header-height` (height:100% + box-sizing) at the shared
//     AURA_HEADER_HEIGHT_PX, so switching profiles (Ctrl+Alt+S / mls.sites.setHeader) shifts nothing;
//   * `bootConfig` + `regionProps` as reactive properties (the shell assigns both);
//   * the mobile aside toggle — the only way to reach the menu when the aside is a drawer;
//   * SPA navigation through auraNavigate, never a raw href.
//
// A subclass implements `renderBand()` and, optionally, `bandCss()` / `renderBrand()`. It must not
// override `createRenderRoot`, declare a height on the host, or use shadow DOM.

import { LitElement, html, nothing } from 'lit';
import { unsafeHTML } from 'lit/directives/unsafe-html.js';
import type { MasterFrontendBootConfig } from '/_102033_/l2/shared/contracts/bootstrap.js';
import type { ProjectNavigationEntry } from '/_102029_/l2/runtimeConfigTypes.js';
import { toggleAuraAside } from '/_102033_/l2/shared/layout/aura-shell-events.js';
import { auraNavigate, auraNavigateFromEvent, isRegionLinkActive } from '/_102033_/l2/shared/layout/auraNavigate.js';
import {
  buildHeaderBandCss,
  buildUserMenuCss,
  resolveBandHeightPx,
  resolveHeaderActions,
  resolveHeaderBrand,
  resolveHeaderLocales,
  resolveHeaderNavHrefs,
  selectNavEntries,
  shouldShowMobileAsideToggle,
  type AuraHeaderAction,
  type AuraHeaderBrand,
} from '/_102033_/l2/shared/layout/auraHeaderCore.js';
import {
  getRuntimeLanguage,
  listRuntimeLanguages,
  setRuntimeLanguage,
} from '/_102033_/l2/shared/languageRuntime.js';
import { getSessionUser, userInitials, userLabel, type SessionUser } from '/_102033_/l2/shared/sessionUser.js';
import {
  getRuntimeDesignSystem,
  listRuntimeDesignSystems,
  setRuntimeDesignSystem,
} from '/_102033_/l2/shared/designSystemRuntime.js';

export type { AuraHeaderAction, AuraHeaderBrand };
export { AURA_HEADER_HEIGHT_PX } from '/_102033_/l2/shared/layout/auraHeaderCore.js';

/** Event a header fires for an action with no route (see `emitHeaderAction`). */
export const AURA_HEADER_ACTION_EVENT = 'collab-aura:header-action';

/** Band CSS is emitted once per tag, not once per render — several profiles can coexist. */
const styledTags = new Set<string>();

export abstract class AuraHeaderBase extends LitElement {
  static properties = {
    bootConfig: { attribute: false },
    regionProps: { attribute: false },
    currentPath: { state: true },
    sessionUser: { state: true },
  };

  declare bootConfig?: MasterFrontendBootConfig;
  /** Profile props handed over by the shell (`brand`, `heightPx`, `props.actions`, `profileName`). */
  declare regionProps?: Record<string, unknown>;
  declare currentPath: string;
  /** Who is logged in (for the avatar); undefined until the one-per-page probe answers. */
  declare sessionUser?: SessionUser;
  /** Guards the probe (once per element) and the broken-photo fallback. */
  private sessionRequested = false;
  private pictureBroken = false;
  private userMenu?: HTMLElement;

  /** Light DOM — the shell's region CSS and the :root DS tokens depend on it. Do NOT override. */
  createRenderRoot() {
    return this;
  }

  connectedCallback() {
    super.connectedCallback();
    this.currentPath = window.location.pathname;
    window.addEventListener('popstate', this.handleLocationChange);
    this.ensureBandStyles();
    // The probe is lazy (see ensureSessionUser): a header that never mentions the user pays nothing,
    // and one that shows the name WITHOUT the avatar still gets it — the earlier version gated the
    // fetch on the `user` action, which left `this.sessionUser` empty for a welcome message.
    if (this.hasAction('user')) this.ensureSessionUser();
  }

  disconnectedCallback() {
    window.removeEventListener('popstate', this.handleLocationChange);
    // The panel lives in the body, so it would outlive a header swapped out by a profile switch.
    this.closeUserMenu();
    super.disconnectedCallback();
  }

  private readonly handleLocationChange = () => {
    this.currentPath = window.location.pathname;
  };

  /** Fires the one-per-page session probe, at most once per element. */
  private ensureSessionUser(): void {
    if (this.sessionRequested) return;
    this.sessionRequested = true;
    void getSessionUser().then((user) => { this.sessionUser = user; });
  }

  /**
   * The logged user's display name (name, else email, else empty) — for a welcome message. Reading it
   * starts the session probe, so a header that greets the user does not have to ask for the avatar.
   */
  protected get userName(): string {
    this.ensureSessionUser();
    return this.sessionUser?.name ?? this.sessionUser?.email ?? '';
  }

  /** First name only, which is what a greeting usually wants. */
  protected get userFirstName(): string {
    const name = this.userName;
    return name.includes('@') ? name.split('@')[0] : name.split(/\s+/u)[0] ?? '';
  }

  protected get userEmail(): string {
    this.ensureSessionUser();
    return this.sessionUser?.email ?? '';
  }

  private ensureBandStyles(): void {
    const tag = this.localName;
    if (!tag || styledTags.has(tag)) {
      return;
    }
    styledTags.add(tag);
    const style = document.createElement('style');
    style.setAttribute('data-aura-header', tag);
    style.textContent = [buildHeaderBandCss(tag), this.bandCss()].filter(Boolean).join('\n\n');
    document.head.appendChild(style);
  }

  // ── Profile-driven state ───────────────────────────────────────────────────

  /** Title used when the profile carries no brand (the master header names itself). */
  protected get fallbackBrandTitle(): string {
    return 'App';
  }

  protected get brand(): AuraHeaderBrand {
    return resolveHeaderBrand(this.bootConfig, this.regionProps, this.fallbackBrandTitle);
  }

  protected get actions(): AuraHeaderAction[] {
    return resolveHeaderActions(this.regionProps);
  }

  protected hasAction(action: AuraHeaderAction): boolean {
    return this.actions.includes(action);
  }

  protected get bandHeightPx(): number {
    return resolveBandHeightPx(this.regionProps);
  }

  protected get basePath(): string {
    return this.bootConfig?.basePath ?? '';
  }

  protected showMobileAsideToggle(): boolean {
    return shouldShowMobileAsideToggle(this.bootConfig);
  }

  /**
   * Message set for the document language, for the `collab_i18n_start/end` block a header carries
   * when it has fixed copy. Resolution is the runtime's own (exact locale, then primary subtag,
   * then the first declared one), so Ctrl+Alt+L switches the header copy along with the pages.
   */
  protected localized<T>(messages: Record<string, T>): T {
    const keys = Object.keys(messages);
    const key = getRuntimeLanguage(keys, document.documentElement.lang) ?? keys[0];
    return messages[key] ?? messages[keys[0]];
  }

  // ── Navigation ─────────────────────────────────────────────────────────────

  /** SPA navigation inside the module, full load elsewhere. Use this, never a bare href. */
  protected navigateTo(href: string): void {
    auraNavigate(href, { basePath: this.basePath });
  }

  protected readonly handleNavigate = (event: Event) => {
    auraNavigateFromEvent(event, { basePath: this.basePath });
  };

  /**
   * Announces a header action that has no route behind it (`user`, `search`, anything app-specific).
   *
   * A header must never invent a route: an action with no destination dispatches this event and the
   * app decides what to do (open a menu, a dialog, nothing at all). The event bubbles, so a listener
   * on window/document sees it.
   */
  protected emitHeaderAction(action: string, detail?: Record<string, unknown>): void {
    this.dispatchEvent(new CustomEvent(AURA_HEADER_ACTION_EVENT, {
      bubbles: true,
      composed: true,
      detail: { action, projectId: this.bootConfig?.projectId, ...detail },
    }));
  }

  // ── Building blocks ────────────────────────────────────────────────────────

  protected renderAsideToggle() {
    return html`
      <button
        class="aura-header-toggle ${this.showMobileAsideToggle() ? 'enabled' : ''}"
        type="button"
        aria-label="Open navigation"
        @click=${() => toggleAuraAside()}
      >
        &#9776;
      </button>
    `;
  }

  /**
   * The mark: inlined markup when the brand carries one (it inherits `currentColor`, so it follows
   * the design system in light and dark), otherwise the `<img>` for a URL. `resolveHeaderBrand`
   * already refused anything unsafe — see `isSafeLogoSvg` — so only a sanitized single `<svg>` root
   * reaches unsafeHTML here. Same shape the 102025 avatar uses.
   */
  protected renderLogo() {
    const brand = this.brand;
    if (brand.logoSvg) {
      return html`<span class="aura-header-logo" role="img" aria-label=${brand.logoAlt ?? brand.title}>${unsafeHTML(brand.logoSvg)}</span>`;
    }
    if (brand.logoUrl) {
      return html`<img class="aura-header-logo" src=${brand.logoUrl} alt=${brand.logoAlt ?? brand.title} />`;
    }
    return nothing;
  }

  protected renderBrand() {
    const brand = this.brand;
    const content = html`
      ${this.renderLogo()}
      <span class="aura-header-brand-text">
        <strong class="aura-header-title">${brand.title}</strong>
        ${brand.subtitle ? html`<span class="aura-header-subtitle">${brand.subtitle}</span>` : nothing}
      </span>
    `;

    return brand.href
      ? html`<a class="aura-header-brand" href=${brand.href} @click=${this.handleNavigate}>${content}</a>`
      : html`<span class="aura-header-brand">${content}</span>`;
  }

  /**
   * The navigation entries this header links: the project's, filtered by the hrefs the profile
   * selected (`props.navLinks`).
   *
   * With NO selection recorded the whole list survives — a band only calls renderNavLinks() when it
   * was asked for links, and headers generated before the field existed have no list to read.
   */
  protected get navEntries(): ProjectNavigationEntry[] {
    return selectNavEntries(
      this.bootConfig?.navigation ?? [],
      this.bootConfig?.moduleLinks ?? [],
      resolveHeaderNavHrefs(this.regionProps),
    );
  }

  protected renderNavLinks(entries: ProjectNavigationEntry[] = this.navEntries) {
    if (entries.length === 0) {
      return nothing;
    }

    return html`
      <nav class="aura-header-nav">
        ${entries.map((entry) => html`
          <a
            class="aura-header-link"
            href=${entry.href}
            title=${entry.description ?? entry.label}
            data-active=${String(isRegionLinkActive(entry.href, this.currentPath, this.basePath))}
            @click=${this.handleNavigate}
          >${entry.label}</a>
        `)}
      </nav>
    `;
  }

  protected renderModuleLinks() {
    return this.renderNavLinks(this.bootConfig?.moduleLinks ?? []);
  }

  protected renderLanguageSwitcher() {
    const languages = resolveHeaderLocales(this.regionProps, listRuntimeLanguages(this.bootConfig?.languages));
    if (languages.length <= 1) {
      return nothing;
    }
    const current = getRuntimeLanguage(languages, document.documentElement.lang);

    return html`
      <select
        class="aura-header-select"
        aria-label="Language"
        .value=${current ?? languages[0]}
        @change=${(event: Event) => setRuntimeLanguage((event.target as HTMLSelectElement).value, languages)}
      >
        ${languages.map((language) => html`<option value=${language} ?selected=${language === current}>${language}</option>`)}
      </select>
    `;
  }

  protected renderDesignSystemSwitcher() {
    const designSystems = listRuntimeDesignSystems(this.bootConfig?.designSystems);
    const projectId = this.bootConfig?.projectId;
    if (designSystems.length <= 1 || !projectId) {
      return nothing;
    }
    const current = getRuntimeDesignSystem(designSystems);

    return html`
      <select
        class="aura-header-select"
        aria-label="Design system"
        .value=${current ?? designSystems[0]}
        @change=${(event: Event) => {
          const designSystem = (event.target as HTMLSelectElement).value;
          void setRuntimeDesignSystem(designSystem, designSystems, projectId)
            .catch((error) => console.warn('[aura-header] design system switch failed:', error));
        }}
      >
        ${designSystems.map((designSystem) => html`<option value=${designSystem} ?selected=${designSystem === current}>${designSystem}</option>`)}
      </select>
    `;
  }

  /**
   * The logged user as an avatar: the IdP photo when there is one, otherwise the initials, otherwise
   * a neutral silhouette. It is a BUTTON — clicking announces the `user` action through
   * `emitHeaderAction`, and the app decides what opens (menu, profile, sign-out).
   *
   * Available to a generated header as `this.renderUserAvatar()`; the profile turns it on by listing
   * the `user` action.
   */
  /** Neutral silhouette for a user with no photo and no initials (anonymous, or an IdP that tells us nothing). */
  private renderAvatarFallbackIcon() {
    return html`
      <svg class="aura-header-avatar-icon" viewBox="0 0 24 24" aria-hidden="true">
        <circle cx="12" cy="8.5" r="3.75" fill="none" stroke="currentColor" stroke-width="1.8"/>
        <path d="M4.75 20c0-3.7 3.25-6 7.25-6s7.25 2.3 7.25 6" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/>
      </svg>
    `;
  }

  protected renderUserAvatar() {
    this.ensureSessionUser();
    const user = this.sessionUser;
    const label = userLabel(user ?? { authenticated: false });
    const initials = user ? userInitials(user) : '';
    // A photo URL that 404s used to leave the browser's broken-image glyph in the band.
    const photo = this.pictureBroken ? undefined : user?.picture;

    return html`
      <button
        class="aura-header-avatar"
        type="button"
        title=${label}
        aria-label=${label}
        aria-haspopup="menu"
        @click=${(event: Event) => this.handleAvatarClick(event)}
      >
        ${photo
          ? html`<img
              class="aura-header-avatar-photo"
              src=${photo}
              alt=""
              referrerpolicy="no-referrer"
              @error=${() => { this.pictureBroken = true; this.requestUpdate(); }}
            />`
          : initials
            ? html`<span class="aura-header-avatar-initials">${initials}</span>`
            : this.renderAvatarFallbackIcon()}
      </button>
    `;
  }

  // ── User menu ──────────────────────────────────────────────────────────────

  /** Copy of the user menu. A subclass with an i18n block overrides this. */
  protected get userMenuLabels(): { signOut: string; anonymous: string } {
    return { signOut: 'Sign out', anonymous: 'Not signed in' };
  }

  private handleAvatarClick(event: Event): void {
    // The app may want to own this entirely — the event fires either way.
    this.emitHeaderAction('user');
    this.toggleUserMenu(event.currentTarget as HTMLElement);
  }

  /**
   * Opens the identity panel under the avatar.
   *
   * Attached to `document.body`, NOT inside the band: the band carries `backdrop-filter`, which makes
   * it a containing block for fixed descendants, and the shell clips the header region with
   * `overflow: hidden` — a panel rendered in place would be cut off instead of shown.
   */
  private toggleUserMenu(anchor: HTMLElement | null): void {
    if (this.userMenu) {
      this.closeUserMenu();
      return;
    }
    if (!anchor) return;

    if (!document.getElementById('aura-user-menu-css')) {
      const style = document.createElement('style');
      style.id = 'aura-user-menu-css';
      style.textContent = buildUserMenuCss();
      document.head.appendChild(style);
    }

    const labels = this.userMenuLabels;
    const menu = document.createElement('div');
    menu.className = 'aura-user-menu';
    menu.setAttribute('role', 'menu');

    const identity = document.createElement('div');
    identity.className = 'aura-user-menu-identity';
    const name = document.createElement('div');
    name.className = 'aura-user-menu-name';
    name.textContent = this.userName || labels.anonymous;
    identity.appendChild(name);
    const email = this.userEmail;
    if (email && email !== name.textContent) {
      const emailLine = document.createElement('div');
      emailLine.className = 'aura-user-menu-email';
      emailLine.textContent = email;
      identity.appendChild(emailLine);
    }
    menu.appendChild(identity);

    const signOut = document.createElement('button');
    signOut.type = 'button';
    signOut.className = 'aura-user-menu-action';
    signOut.setAttribute('role', 'menuitem');
    signOut.textContent = labels.signOut;
    signOut.addEventListener('click', () => { void this.signOut(); });
    menu.appendChild(signOut);

    document.body.appendChild(menu);
    const rect = anchor.getBoundingClientRect();
    const width = menu.offsetWidth;
    menu.style.top = `${Math.round(rect.bottom + 8)}px`;
    // Right-aligned with the avatar, kept inside the viewport.
    menu.style.left = `${Math.round(Math.max(12, Math.min(rect.right - width, window.innerWidth - width - 12)))}px`;
    signOut.focus();

    this.userMenu = menu;
    window.addEventListener('keydown', this.handleUserMenuKeydown, true);
    window.addEventListener('pointerdown', this.handleOutsidePointer, true);
    window.addEventListener('resize', this.closeUserMenu);
  }

  private readonly closeUserMenu = (): void => {
    if (!this.userMenu) return;
    this.userMenu.remove();
    this.userMenu = undefined;
    window.removeEventListener('keydown', this.handleUserMenuKeydown, true);
    window.removeEventListener('pointerdown', this.handleOutsidePointer, true);
    window.removeEventListener('resize', this.closeUserMenu);
  };

  private readonly handleUserMenuKeydown = (event: KeyboardEvent): void => {
    if (event.key === 'Escape') this.closeUserMenu();
  };

  private readonly handleOutsidePointer = (event: Event): void => {
    const target = event.target as Node | null;
    if (!target || this.userMenu?.contains(target) || this.contains(target)) return;
    this.closeUserMenu();
  };

  /**
   * Ends the session. Uses the runtime hook when the page has it (window.collabRuntimeAuth), and
   * falls back to importing the auth helper on demand — the header never pays for it until a click.
   */
  protected async signOut(): Promise<void> {
    this.closeUserMenu();
    const hook = (window as unknown as { collabRuntimeAuth?: { logout?: () => Promise<void> } }).collabRuntimeAuth;
    if (typeof hook?.logout === 'function') {
      await hook.logout();
      return;
    }
    try {
      const auth = await import('/_102033_/l2/cbe/cbeAuth.js') as { logoutCollab?: () => Promise<void> };
      if (typeof auth.logoutCollab === 'function') {
        await auth.logoutCollab();
        return;
      }
    } catch (error) {
      console.warn('[aura-header] could not load the auth helper', error);
    }
    window.location.reload();
  }

  /**
   * The optional actions the profile enabled, in a stable order. `search` has no shell runtime behind
   * it: a subclass that declares it renders it itself (see `hasAction`). `user` is the avatar, which
   * the base draws — a subclass may still place it by hand with `renderUserAvatar()`.
   */
  protected renderActions() {
    const actions = this.actions;
    if (actions.length === 0) {
      return nothing;
    }

    return html`
      ${actions.includes('modules') ? this.renderModuleLinks() : nothing}
      ${actions.includes('language') ? this.renderLanguageSwitcher() : nothing}
      ${actions.includes('designSystem') ? this.renderDesignSystemSwitcher() : nothing}
      ${actions.includes('user') ? this.renderUserAvatar() : nothing}
    `;
  }

  // ── Subclass surface ───────────────────────────────────────────────────────

  /** Extra CSS for this subclass, injected once per tag. Scope every rule with its own tag. */
  protected bandCss(): string {
    return '';
  }

  /** The band's content. Everything around it (band, height, styles) belongs to the base. */
  protected abstract renderBand(): unknown;

  render() {
    return html`<header class="aura-header-band">${this.renderBand()}</header>`;
  }
}
