/// <mls fileReference="_102033_/l2/shared/layout/aura-header-base.ts" enhancement="_blank" />

// Base of EVERY client header: the master's own (`collab-aura-header`) and the per-project ones
// generated by agentGenerateHeader. It owns the invariants the shell depends on, which used to live
// as comments and convention inside a single header file:
//
//   * light DOM (`createRenderRoot`) — the shell styles region descendants and the DS tokens are on :root;
//   * the `<header>` band filling `--aura-header-height` (height:100% + box-sizing) at the shared
//     AURA_HEADER_HEIGHT_PX, so switching profiles (Ctrl+Alt+S / mls.sites.setHeader) shifts nothing;
//   * `bootConfig` + `regionProps` as reactive properties (the shell assigns both);
//   * the mobile aside toggle — the only way to reach the menu when the aside is a drawer;
//   * SPA navigation through auraNavigate, never a raw href.
//
// A subclass implements `renderBand()` and, optionally, `bandCss()` / `renderBrand()`. It must not
// override `createRenderRoot`, declare a height on the host, or use shadow DOM.

import { LitElement, html, nothing } from 'lit';
import { unsafeHTML } from 'lit/directives/unsafe-html.js';
import type { MasterFrontendBootConfig } from '/_102033_/l2/shared/contracts/bootstrap.js';
import type { ProjectNavigationEntry } from '/_102029_/l2/runtimeConfigTypes.js';
import { toggleAuraAside } from '/_102033_/l2/shared/layout/aura-shell-events.js';
import { auraNavigate, auraNavigateFromEvent, isRegionLinkActive } from '/_102033_/l2/shared/layout/auraNavigate.js';
import {
  buildHeaderBandCss,
  resolveBandHeightPx,
  resolveHeaderActions,
  resolveHeaderBrand,
  shouldShowMobileAsideToggle,
  type AuraHeaderAction,
  type AuraHeaderBrand,
} from '/_102033_/l2/shared/layout/auraHeaderCore.js';
import {
  getRuntimeLanguage,
  listRuntimeLanguages,
  setRuntimeLanguage,
} from '/_102033_/l2/shared/languageRuntime.js';
import {
  getRuntimeDesignSystem,
  listRuntimeDesignSystems,
  setRuntimeDesignSystem,
} from '/_102033_/l2/shared/designSystemRuntime.js';

export type { AuraHeaderAction, AuraHeaderBrand };
export { AURA_HEADER_HEIGHT_PX } from '/_102033_/l2/shared/layout/auraHeaderCore.js';

/** Event a header fires for an action with no route (see `emitHeaderAction`). */
export const AURA_HEADER_ACTION_EVENT = 'collab-aura:header-action';

/** Band CSS is emitted once per tag, not once per render — several profiles can coexist. */
const styledTags = new Set<string>();

export abstract class AuraHeaderBase extends LitElement {
  static properties = {
    bootConfig: { attribute: false },
    regionProps: { attribute: false },
    currentPath: { state: true },
  };

  declare bootConfig?: MasterFrontendBootConfig;
  /** Profile props handed over by the shell (`brand`, `heightPx`, `props.actions`, `profileName`). */
  declare regionProps?: Record<string, unknown>;
  declare currentPath: string;

  /** Light DOM — the shell's region CSS and the :root DS tokens depend on it. Do NOT override. */
  createRenderRoot() {
    return this;
  }

  connectedCallback() {
    super.connectedCallback();
    this.currentPath = window.location.pathname;
    window.addEventListener('popstate', this.handleLocationChange);
    this.ensureBandStyles();
  }

  disconnectedCallback() {
    window.removeEventListener('popstate', this.handleLocationChange);
    super.disconnectedCallback();
  }

  private readonly handleLocationChange = () => {
    this.currentPath = window.location.pathname;
  };

  private ensureBandStyles(): void {
    const tag = this.localName;
    if (!tag || styledTags.has(tag)) {
      return;
    }
    styledTags.add(tag);
    const style = document.createElement('style');
    style.setAttribute('data-aura-header', tag);
    style.textContent = [buildHeaderBandCss(tag), this.bandCss()].filter(Boolean).join('\n\n');
    document.head.appendChild(style);
  }

  // ── Profile-driven state ───────────────────────────────────────────────────

  /** Title used when the profile carries no brand (the master header names itself). */
  protected get fallbackBrandTitle(): string {
    return 'App';
  }

  protected get brand(): AuraHeaderBrand {
    return resolveHeaderBrand(this.bootConfig, this.regionProps, this.fallbackBrandTitle);
  }

  protected get actions(): AuraHeaderAction[] {
    return resolveHeaderActions(this.regionProps);
  }

  protected hasAction(action: AuraHeaderAction): boolean {
    return this.actions.includes(action);
  }

  protected get bandHeightPx(): number {
    return resolveBandHeightPx(this.regionProps);
  }

  protected get basePath(): string {
    return this.bootConfig?.basePath ?? '';
  }

  protected showMobileAsideToggle(): boolean {
    return shouldShowMobileAsideToggle(this.bootConfig);
  }

  /**
   * Message set for the document language, for the `collab_i18n_start/end` block a header carries
   * when it has fixed copy. Resolution is the runtime's own (exact locale, then primary subtag,
   * then the first declared one), so Ctrl+Alt+L switches the header copy along with the pages.
   */
  protected localized<T>(messages: Record<string, T>): T {
    const keys = Object.keys(messages);
    const key = getRuntimeLanguage(keys, document.documentElement.lang) ?? keys[0];
    return messages[key] ?? messages[keys[0]];
  }

  // ── Navigation ─────────────────────────────────────────────────────────────

  /** SPA navigation inside the module, full load elsewhere. Use this, never a bare href. */
  protected navigateTo(href: string): void {
    auraNavigate(href, { basePath: this.basePath });
  }

  protected readonly handleNavigate = (event: Event) => {
    auraNavigateFromEvent(event, { basePath: this.basePath });
  };

  /**
   * Announces a header action that has no route behind it (`user`, `search`, anything app-specific).
   *
   * A header must never invent a route: an action with no destination dispatches this event and the
   * app decides what to do (open a menu, a dialog, nothing at all). The event bubbles, so a listener
   * on window/document sees it.
   */
  protected emitHeaderAction(action: string, detail?: Record<string, unknown>): void {
    this.dispatchEvent(new CustomEvent(AURA_HEADER_ACTION_EVENT, {
      bubbles: true,
      composed: true,
      detail: { action, projectId: this.bootConfig?.projectId, ...detail },
    }));
  }

  // ── Building blocks ────────────────────────────────────────────────────────

  protected renderAsideToggle() {
    return html`
      <button
        class="aura-header-toggle ${this.showMobileAsideToggle() ? 'enabled' : ''}"
        type="button"
        aria-label="Open navigation"
        @click=${() => toggleAuraAside()}
      >
        &#9776;
      </button>
    `;
  }

  /**
   * The mark: inlined markup when the brand carries one (it inherits `currentColor`, so it follows
   * the design system in light and dark), otherwise the `<img>` for a URL. `resolveHeaderBrand`
   * already refused anything unsafe — see `isSafeLogoSvg` — so only a sanitized single `<svg>` root
   * reaches unsafeHTML here. Same shape the 102025 avatar uses.
   */
  protected renderLogo() {
    const brand = this.brand;
    if (brand.logoSvg) {
      return html`<span class="aura-header-logo" role="img" aria-label=${brand.logoAlt ?? brand.title}>${unsafeHTML(brand.logoSvg)}</span>`;
    }
    if (brand.logoUrl) {
      return html`<img class="aura-header-logo" src=${brand.logoUrl} alt=${brand.logoAlt ?? brand.title} />`;
    }
    return nothing;
  }

  protected renderBrand() {
    const brand = this.brand;
    const content = html`
      ${this.renderLogo()}
      <span class="aura-header-brand-text">
        <strong class="aura-header-title">${brand.title}</strong>
        ${brand.subtitle ? html`<span class="aura-header-subtitle">${brand.subtitle}</span>` : nothing}
      </span>
    `;

    return brand.href
      ? html`<a class="aura-header-brand" href=${brand.href} @click=${this.handleNavigate}>${content}</a>`
      : html`<span class="aura-header-brand">${content}</span>`;
  }

  protected renderNavLinks(entries: ProjectNavigationEntry[] = this.bootConfig?.navigation ?? []) {
    if (entries.length === 0) {
      return nothing;
    }

    return html`
      <nav class="aura-header-nav">
        ${entries.map((entry) => html`
          <a
            class="aura-header-link"
            href=${entry.href}
            title=${entry.description ?? entry.label}
            data-active=${String(isRegionLinkActive(entry.href, this.currentPath, this.basePath))}
            @click=${this.handleNavigate}
          >${entry.label}</a>
        `)}
      </nav>
    `;
  }

  protected renderModuleLinks() {
    return this.renderNavLinks(this.bootConfig?.moduleLinks ?? []);
  }

  protected renderLanguageSwitcher() {
    const languages = listRuntimeLanguages(this.bootConfig?.languages);
    if (languages.length <= 1) {
      return nothing;
    }
    const current = getRuntimeLanguage(languages, document.documentElement.lang);

    return html`
      <select
        class="aura-header-select"
        aria-label="Language"
        .value=${current ?? languages[0]}
        @change=${(event: Event) => setRuntimeLanguage((event.target as HTMLSelectElement).value, languages)}
      >
        ${languages.map((language) => html`<option value=${language} ?selected=${language === current}>${language}</option>`)}
      </select>
    `;
  }

  protected renderDesignSystemSwitcher() {
    const designSystems = listRuntimeDesignSystems(this.bootConfig?.designSystems);
    const projectId = this.bootConfig?.projectId;
    if (designSystems.length <= 1 || !projectId) {
      return nothing;
    }
    const current = getRuntimeDesignSystem(designSystems);

    return html`
      <select
        class="aura-header-select"
        aria-label="Design system"
        .value=${current ?? designSystems[0]}
        @change=${(event: Event) => {
          const designSystem = (event.target as HTMLSelectElement).value;
          void setRuntimeDesignSystem(designSystem, designSystems, projectId)
            .catch((error) => console.warn('[aura-header] design system switch failed:', error));
        }}
      >
        ${designSystems.map((designSystem) => html`<option value=${designSystem} ?selected=${designSystem === current}>${designSystem}</option>`)}
      </select>
    `;
  }

  /**
   * The optional actions the profile enabled, in a stable order. `search` and `user` have no shell
   * runtime behind them: a subclass that declares them renders them itself (see `hasAction`).
   */
  protected renderActions() {
    const actions = this.actions;
    if (actions.length === 0) {
      return nothing;
    }

    return html`
      ${actions.includes('modules') ? this.renderModuleLinks() : nothing}
      ${actions.includes('language') ? this.renderLanguageSwitcher() : nothing}
      ${actions.includes('designSystem') ? this.renderDesignSystemSwitcher() : nothing}
    `;
  }

  // ── Subclass surface ───────────────────────────────────────────────────────

  /** Extra CSS for this subclass, injected once per tag. Scope every rule with its own tag. */
  protected bandCss(): string {
    return '';
  }

  /** The band's content. Everything around it (band, height, styles) belongs to the base. */
  protected abstract renderBand(): unknown;

  render() {
    return html`<header class="aura-header-band">${this.renderBand()}</header>`;
  }
}
